print('Find the perimeter of a polygon with 3 to 15 sides!')
print('Write the number of sides here: (up to 15)')
ns = input()
if ns == '3':	
	print('Please write the first side length here:')
	s1 = float(input())
	print('Please write the next side length here:') 
	s2 = float(input())
	print('Please write the next side length here:') 
	s3 = float(input())
	print("Here is your answer:")
	print(s1 + s2 + s3)
elif ns == '4':
	print('Please write the first side length here:')
	s1 = float(input())
	print('Please write the next side length here:') 
	s2 = float(input())
	print('Please write the next side length here:') 
	s3 = float(input())
	print('Please write the next side length here:') 
	s4 = float(input())
	print("Here is your answer:")
	print(s1 + s2 + s3 + s4)
elif ns == '5':	
	print('Please write the first side length here:')
	s1 = float(input())
	print('Please write the next side length here:') 
	s2 = float(input())
	print('Please write the next side length here:') 
	s3 = float(input())
	print('Please write the next side length here:') 
	s4 = float(input())
	print('Please write the next side length here:') 
	s5 = float(input())
	print("Here is your answer:")
	print(s1 + s2 + s3 + s4 + s5)
elif ns == '6':
	print('Please write the first side length here:')
	s1 = float(input())
	print('Please write the next side length here:') 
	s2 = float(input())
	print('Please write the next side length here:') 
	s3 = float(input())
	print('Please write the next side length here:') 
	s4 = float(input())
	print('Please write the next side length here:') 
	s5 = float(input())
	print('Please write the next side length here:') 
	s6 = float(input())
	print(s1 + s2 + s3 + s4 + s5 + s6)
elif ns == '7':	
	print('Please write the first side length here:')
	s1 = float(input())
	print('Please write the next side length here:') 
	s2 = float(input())
	print('Please write the next side length here:') 
	s3 = float(input())
	print('Please write the next side length here:') 
	s4 = float(input())
	print('Please write the next side length here:') 
	s5 = float(input())
	print('Please write the next side length here:') 
	s6 = float(input())
	print('Please write the next side length here:') 
	s7 = float(input())
	print("Here is your answer:")
	print(s1 + s2 + s3 + s4 + s5 + s6 + s7)
elif ns == '8':
	print('Please write the first side length here:')
	s1 = float(input())
	print('Please write the next side length here:') 
	s2 = float(input())
	print('Please write the next side length here:') 
	s3 = float(input())
	print('Please write the next side length here:') 
	s4 = float(input())
	print('Please write the next side length here:') 
	s5 = float(input())
	print('Please write the next side length here:') 
	s6 = float(input())
	print('Please write the next side length here:') 
	s7 = float(input())
	print('Please write the next side length here:') 
	s8 = float(input())
	print("Here is your answer:")
	print(s1 + s2 + s3 + s4 + s5 + s6 + s7 + s8)
elif ns == '9':	
	print('Please write the first side length here:')
	s1 = float(input())
	print('Please write the next side length here:') 
	s2 = float(input())
	print('Please write the next side length here:') 
	s3 = float(input())
	print('Please write the next side length here:') 
	s4 = float(input())
	print('Please write the next side length here:') 
	s5 = float(input())
	print('Please write the next side length here:') 
	s6 = float(input())
	print('Please write the next side length here:') 
	s7 = float(input())
	print('Please write the next side length here:') 
	s8 = float(input())
	print('Please write the next side length here:') 
	s9 = float(input())
	print("Here is your answer:")
	print(s1 + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9)
elif ns == '10':
	print('Please write the first side length here:')
	s1 = float(input())
	print('Please write the next side length here:') 
	s2 = float(input())
	print('Please write the next side length here:') 
	s3 = float(input())
	print('Please write the next side length here:') 
	s4 = float(input())
	print('Please write the next side length here:') 
	s5 = float(input())
	print('Please write the next side length here:') 
	s6 = float(input())
	print('Please write the next side length here:') 
	s7 = float(input())
	print('Please write the next side length here:') 
	s8 = float(input())
	print('Please write the next side length here:') 
	s9 = float(input())
	print('Please write the next side length here:') 
	s10 = float(input())
	print("Here is your answer:")
	print(s1 + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + s10)
elif ns == '11':	
	print('Please write the first side length here:')
	s1 = float(input())
	print('Please write the next side length here:') 
	s2 = float(input())
	print('Please write the next side length here:') 
	s3 = float(input())
	print('Please write the next side length here:') 
	s4 = float(input())
	print('Please write the next side length here:') 
	s5 = float(input())
	print('Please write the next side length here:') 
	s6 = float(input())
	print('Please write the next side length here:') 
	s7 = float(input())
	print('Please write the next side length here:') 
	s8 = float(input())
	print('Please write the next side length here:') 
	s9 = float(input())
	print('Please write the next side length here:') 
	s10 = float(input())
	print('Please write the next side length here:') 
	s11 = float(input())
	print("Here is your answer:")
	print(s1 + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + s10 + s11)
elif ns == '12':
	print('Please write the first side length here:')
	s1 = float(input())
	print('Please write the next side length here:') 
	s2 = float(input())
	print('Please write the next side length here:') 
	s3 = float(input())
	print('Please write the next side length here:') 
	s4 = float(input())
	print('Please write the next side length here:') 
	s5 = float(input())
	print('Please write the next side length here:') 
	s6 = float(input())
	print('Please write the next side length here:') 
	s7 = float(input())
	print('Please write the next side length here:') 
	s8 = float(input())
	print('Please write the next side length here:') 
	s9 = float(input())
	print('Please write the next side length here:') 
	s10 = float(input())
	print('Please write the next side length here:') 
	s11 = float(input())
	print('Please write the next side length here:') 
	s12 = float(input())
	print("Here is your answer:")
	print(s1 + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + s10 + s11 + s12)
elif ns == '13':	
	print('Please write the first side length here:')
	s1 = float(input())
	print('Please write the next side length here:') 
	s2 = float(input())
	print('Please write the next side length here:') 
	s3 = float(input())
	print('Please write the next side length here:') 
	s4 = float(input())
	print('Please write the next side length here:') 
	s5 = float(input())
	print('Please write the next side length here:') 
	s6 = float(input())
	print('Please write the next side length here:') 
	s7 = float(input())
	print('Please write the next side length here:') 
	s8 = float(input())
	print('Please write the next side length here:') 
	s9 = float(input())
	print('Please write the next side length here:') 
	s10 = float(input())
	print('Please write the next side length here:') 
	s11 = float(input())
	print('Please write the next side length here:') 
	s12 = float(input())
	print('Please write the next side length here:') 
	s13 = float(input())
	print("Here is your answer:")
	print(s1 + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + s10 + s11 + s12 + s13)
elif ns == '14':
	print('Please write the first side length here:')
	s1 = float(input())
	print('Please write the next side length here:') 
	s2 = float(input())
	print('Please write the next side length here:') 
	s3 = float(input())
	print('Please write the next side length here:') 
	s4 = float(input())
	print('Please write the next side length here:') 
	s5 = float(input())
	print('Please write the next side length here:') 
	s6 = float(input())
	print('Please write the next side length here:') 
	s7 = float(input())
	print('Please write the next side length here:') 
	s8 = float(input())
	print('Please write the next side length here:') 
	s9 = float(input())
	print('Please write the next side length here:') 
	s10 = float(input())
	print('Please write the next side length here:') 
	s11 = float(input())
	print('Please write the next side length here:') 
	s12 = float(input())
	print('Please write the next side length here:') 
	s13 = float(input())
	print('Please write the next side length here:') 
	s14 = float(input())
	print("Here is your answer:")
	print(s1 + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + s10 + s11 + s12 + s13 + s14)
elif ns == '15':	
	print('Please write the first side length here:')
	s1 = float(input())
	print('Please write the next side length here:') 
	s2 = float(input())
	print('Please write the next side length here:') 
	s3 = float(input())
	print('Please write the next side length here:') 
	s4 = float(input())
	print('Please write the next side length here:') 
	s5 = float(input())
	print('Please write the next side length here:') 
	s6 = float(input())
	print('Please write the next side length here:') 
	s7 = float(input())
	print('Please write the next side length here:') 
	s8 = float(input())
	print('Please write the next side length here:') 
	s9 = float(input())
	print('Please write the next side length here:') 
	s10 = float(input())
	print('Please write the next side length here:') 
	s11 = float(input())
	print('Please write the next side length here:') 
	s12 = float(input())
	print('Please write the next side length here:') 
	s13 = float(input())
	print('Please write the next side length here:') 
	s14 = float(input())
	print('Please write the next side length here:') 
	s15 = float(input())
	print("Here is your answer:")
	print(s1 + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + s10 + s11 + s12 + s13 + s14 + s15)
else:
	print("Entry is not valid")
#start calculator again on keypress Enter	
print("\n \nPress Enter to Clear and Calculate Again")
input("")
import replit
import time
replit.clear()

a = 1

while a < 1:
    a += 1
    time.sleep(1)
    replit.clear()
import subprocess
subprocess.call(['python', 'main.py'])